Move stupidtable.js into application.js.
Fixes this javascript error:

    Uncaught TypeError: $(...).stupidtable is not a function

on these pages:

* http://safebooru.donmai.us/reports/user_promotions
* http://safebooru.donmai.us/reports/contributors
* http://safebooru.donmai.us/reports/janitor_trials

...due to stupidtable.js not loading.