docker: fix Postgres shared memory errors.
Fix errors like this from Postgres:

    ERROR:  could not resize shared memory segment "/PostgreSQL.1657512124" to 67145824 bytes: No space left on device

Caused by /dev/shm being too small (64MB by default) when running in Docker.